[package]
name = "blokmap-backend"
version = "0.1.0"
authors=[
	"Ewout Verlinde <ewout@gentsestudentenraad.be>",
    "Tibo Ulens <tibo@gentsestudentenraad.be>",
]
edition = "2024"
readme="README.md"
license-file="LICENSE"
publish=false

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1

[dependencies]
