[package]
name = "blokmap-backend"
version = "0.1.0"
authors=[
	"Ewout Verlinde <ewout@gentsestudentenraad.be>",
    "Tibo Ulens <tibo@gentsestudentenraad.be>",
]
edition = "2024"
readme="README.md"
license-file="LICENSE"
publish=false

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1

[dependencies]
argon2 = "0.5.3"
axum = { version="0.8.1", features=["macros"] }
chrono = { version="0.4.40", features=["serde"] }
deadpool-diesel = { version="0.6.1", features=["postgres", "tracing"] }
diesel = { version="2.2.7", features=["postgres", "chrono"]}
diesel-derive-enum = { version="2.1.0", features=["postgres"] }
serde = { version="1.0.218", features=["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"
tokio = { version="1.43.0", features=["rt-multi-thread", "macros", "parking_lot", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
validator = "0.20.0"
validator_derive = "0.20.0"
