[workspace]
members = ["blokmap", "seeder"]

[workspace.dependencies]
deadpool-diesel = { version = "0.6.1", features = ["postgres", "tracing"] }
diesel = { version = "2.2.10", features = [
    "postgres",
    "chrono",
    "serde_json",
    "uuid",
] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
diesel-dynamic-schema = "0.2.3"

tokio = { version = "1.45.1", features = [
    "macros",
    "parking_lot",
    "rt",
    "rt-multi-thread",
    "signal",
    "tracing",
] }
