[package]
name = "blokmap"
version = "0.1.0"
authors = [
    "Ewout Verlinde <ewout@gentsestudentenraad.be>",
    "Tibo Ulens <tibo@gentsestudentenraad.be>",
]
edition = "2024"
readme = "README.md"
license-file = "LICENSE"
publish = false

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1

[dependencies]
argon2 = "0.5.3"
axum = { version = "0.8.1", features = ["macros"] }
axum-extra = { version = "0.10.0", features = ["cookie", "cookie-private"] }
chrono = { version = "0.4.40", features = ["serde"] }
deadpool-diesel = { version = "0.6.1", features = ["postgres", "tracing"] }
diesel = { version = "2.2.7", features = [
	"postgres",
	"chrono",
	"uuid",
	"i-implement-a-third-party-backend-and-opt-into-breaking-changes",
] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
lettre = { version = "0.11.14", features = ["tracing"] }
openssl = "*"
parking_lot = "0.12.3"
redis = { version = "0.29.1", features = ["tokio-comp", "uuid"] }
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"
time = "0.3.37"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = [
    "compression-full",
    "decompression-full",
    "timeout",
    "trace",
] }
tokio = { version = "1.43.0", features = [
    "macros",
    "parking_lot",
    "rt",
    "rt-multi-thread",
    "signal",
    "tracing",
] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.15.1", features = ["v4", "serde"] }
validator = "0.20.0"
validator_derive = "0.20.0"
diesel-derive-newtype = "2.1.2"

[dev-dependencies]
axum-test = "17.2.0"
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
futures = "0.3.31"
http-body-util = "0.1.2"
mime = "0.3.17"
