FROM rust:1.87.0-slim

# Install dependency for postgres and healthcheck
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update \
    && apt install -y libpq5 libpq-dev curl pkg-config openssl libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install --locked cargo-watch

WORKDIR /blokmap-backend

COPY . .

CMD ["cargo", "watch", "-x", "run"]
