FROM rust:slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y curl

RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

RUN cargo binstall diesel_cli

COPY ./migrations ./migrations

ENTRYPOINT [ "diesel" ]
CMD [ "migration", "run" ]
