name: Common python steps
description: Sets up python and poetry with caching

runs:
    using: composite
    steps:
    #   - name: Setup python
    #     uses: actions/setup-python@v5
    #     with:
    #         python-version: "3.13"

      - name: Setup python
        shell: bash
        run: |
            sudo apt install python3 python3-dev python3-venv
            sudo ln -s /bin/python3 /bin/python

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
            path: ~/.local
            key: poetry-1

      - name: Install and configure Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
            virtualenvs-create: true
            virtualenvs-path: .venv
            virtualenvs-in-project: true

      - name: Configure poetry
        if: steps.cached-poetry.outputs.cache-hit == 'true'
        shell: bash
        run: |
            poetry config virtualenvs.create true
            poetry config virtualenvs.path .venv
            poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-deps
        uses: actions/cache@v4
        with:
            path: .venv
            key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-deps.outputs.cache-hit != 'true'
        shell: bash
        run: poetry install --no-interaction --no-root

      - name: Source venv
        shell: bash
        run: source .venv/bin/activate
