name: Build and release a new docker image

permissions:
    packages: write
    contents: read

on:
    push:
        tags: ["v*"]

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml

    create-release-draft:
        runs-on: self-hosted
        needs: ci
        permissions:
            contents: write
        steps:
          - name: Parse tag
            id: parse_tag
            run: "echo \"version=$(echo ${{ github.ref }} | sed 's#^refs/tags/v##')\" >> $GITHUB_OUTPUT"

          - uses: release-drafter/release-drafter@v6
            with:
                name: v${{ steps.parse_tag.outputs.version }}
                tag: v${{ steps.parse_tag.outputs.version }}
                version: v${{ steps.parse_tag.outputs.version }}
                config-name: release-drafter.yaml
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release-backend-package:
        runs-on: self-hosted
        needs: ci
        steps:
          - name: Load docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: |
                    ghcr.io/blokmap/blokmap-backend
                tags: |
                    type=semver,pattern={{version}}

          - name: Login to GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
                file: Dockerfile.prod
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                cache-from: type=registry,ref=ghcr.io/blokmap/blokmap-backend:buildcache
                cache-to: type=registry,ref=ghcr.io/blokmap/blokmap-backend:buildcache,mode=max

    release-migrations-package:
        runs-on: self-hosted
        needs: ci
        steps:
          - name: Load docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: |
                    ghcr.io/blokmap/blokmap-migrations
                tags: |
                    type=semver,pattern={{version}}

          - name: Login to GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
                file: Dockerfile.migrations
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                cache-from: type=registry,ref=ghcr.io/blokmap/blokmap-migrations:buildcache
                cache-to: type=registry,ref=ghcr.io/blokmap/blokmap-migrations:buildcache,mode=max

    deploy:
        runs-on: self-hosted
        needs: [release-backend-package, release-migrations-package]
        steps:
          - name: Run migrations
            uses: appleboy/ssh-action@v1.2.1
            with:
                host: ${{ secrets.PRODUCTION_HOST }}
                username: ${{ secrets.PRODUCTION_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                debug: true
                script: |
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml up blokmap-staging-migrations

          - name: Deploy backend
            uses: appleboy/ssh-action@v1.2.1
            with:
                host: ${{ secrets.PRODUCTION_HOST }}
                username: ${{ secrets.PRODUCTION_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                debug: true
                script: |
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml up blokmap-staging-backend -d
