name: Lint and test code

on:
    push:
        branches-ignore: ["main", "staging"]
        tags-ignore: ["**"]

    workflow_call:

jobs:
    lint:
        runs-on: self-hosted

        steps:
            - name: Vague chown hack
              run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build images
              run: |
                  docker compose \
                  -f .github/compose.yaml \
                  --project-directory . \
                  build

            - name: Lint code
              run: |
                  docker compose \
                  -f .github/compose.yaml \
                  --project-directory . \
                  run lint

    test:
        runs-on: self-hosted

        steps:
            - name: Vague chown hack
              run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build images
              run: |
                  docker compose \
                  -f .github/compose.yaml \
                  --project-directory . \
                  build

            - name: Run tests
              run: |
                  docker compose \
                  -f .github/compose.yaml \
                  --project-directory . \
                  run test
