name: Lint, format, and test code

on:
    push:
        branches: ["**"]
        tags-ignore: ["**"]

    workflow_call:

jobs:
    lint-and-format:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup
            uses: ./.github/actions/common

          - name: Lint code
            run: poetry run task lint

          - name: Format code
            run: poetry run task format

    test:
        runs-on: ubuntu-latest

        env:
            DATABASE_USER: blokmap-test
            DATABASE_PASSWORD: blokmap-test
            DATABASE_HOST: test-database
            DATABASE_NAME: blokmap-test

        services:
            test-database:
                image: postgres
                env:
                    PGUSER: blokmap-test
                    POSTGRES_USER: blokmap-test
                    POSTGRES_PASSWORD: blokmap-test
                    POSTGRES_DB: blokmap-test
                ports:
                  - "5432:5432"

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup
            uses: ./.github/actions/common

          - name: Run tests
            run: poetry run task test
